version: '3'

services:
  app:
    image: golang:alpine
    volumes:
      - ./src:/app
    working_dir: /app
    command: "go run main.go"
    ports:
      - 3000:3000
    environment:
      - GOPROXY=goproxy.cn
    container_name: app